//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonebookTheOneApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardID { get; set; }
        public int TypeOfCardID { get; set; }
        public int PersonID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual TypeOfCard TypeOfCard { get; set; }
    }
}
