//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonebookTheOneApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorRoom
    {
        public int FloorRoomID { get; set; }
        public int FloorNumber { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Room Room { get; set; }
    }
}
