//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonebookTheOneApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Phonebook2Entities : DbContext
    {
        public Phonebook2Entities()
            : base("name=Phonebook2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FloorRoom> FloorRooms { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguagePerson> LanguagePersons { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonTitle> PersonTitles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<TypeOfCard> TypeOfCards { get; set; }
    }
}
